### ISSUE TITLE
Design Washer Project

### ISSUE THREAD

**Issue by LeonelNieto** [LeonelNL/TIVA-Lavadora#1]
## Overview
Design washer project, documentation and create tickets

## Design considerations

- Serial communication
- Types of cycles.
- Times of cycles
- Selection between LabView or physical

## Requirements:

_Link the classroom_

## Definition of done
- [x] Definition of the project.
- [x] List of materials.
- [x] behavior diagram

**Comment by LeonelNL** [comment]
![Machine State Washer drawio](https://user-images.githubusercontent.com/110416710/196056687-683d5425-ee6a-46a9-8d82-90e789096954.png)

**Comment by LeonelNL** [comment]
[Lista de pines.txt](https://github.com/LeonelNL/TIVA-Lavadora/files/9795890/Lista.de.pines.txt)
